### ISSUE TITLE
Create service alias / make services configureable

### ISSUE THREAD

**Issue by migo315** [bestit/odm-param-converter-bundle#5]
Currently, the `best_it.commercetools_odm.manager` service will directly used in service decleration. This service comes from another bundle and should used only aliased. 

```
    best_it_odmparam_converter.converter.odmconverter:
        class: BestIt\ODMParamConverterBundle\Converter\ODMConverter
        arguments:
            - '@best_it.commercetools_odm.manager'
        tags:
            - { name: request.param_converter }
```
